### ISSUE TITLE
Relicense {fmt} to make it more friendly for standard library vendors

### ISSUE THREAD

**Issue by vitaut** [fmtlib/fmt#1073]
According to Billy O'Neal, the standard library vendors (including libstdc++) all can't look at BSD-licensed code. To fix this we need to drop all requirements on binary redistribution, e.g. introduce a clause similar to "LLVM Exceptions to the Apache 2.0 License":

> As an exception, if, as a result of your compiling your source code, portions
of this Software are embedded into an Object form of such source code, you
may redistribute such embedded portions in such Object form without complying
with the conditions of Sections 4(a), 4(b) and 4(d) of the License.

> In addition, if you combine or link compiled forms of this Software with
software that is licensed under the GPLv2 ("Combined Software") and if a
court of competent jurisdiction determines that the patent provision (Section
3), the indemnity provision (Section 9) or other Section of the License
conflicts with the conditions of the GPLv2, you may retroactively and
prospectively choose to deem waived or otherwise exclude such Section(s) of
the License, but only in their entirety and only with respect to the Combined
Software.

See also http://llvm.org/foundation/relicensing/

Also might be a good time to introduce CLA: https://github.com/cla-assistant/cla-assistant

 List of current library contributors from blame: 

* [x] Victor Zverovich (vitaut)
* [x] Ivan Shynkarenka (chronoxor): https://github.com/fmtlib/fmt/pull/1075#issuecomment-471654313
* [x] Jason Shuo Zang (jasonszang): https://github.com/fmtlib/fmt/pull/1078#issuecomment-472484229
* [x] Daniela Engert (DanielaE): https://github.com/fmtlib/fmt/issues/1073#issuecomment-473688894
* [x] Elias Kosunen (eliaskosunen): https://github.com/fmtlib/fmt/issues/1073#issuecomment-473705496
* [x] Jonathan Müller (foonathan): https://github.com/fmtlib/fmt/pull/1083#issue-261871368
* [x] Brian Ricciardelli (ricco19, Brian): https://github.com/fmtlib/fmt/pull/1086#issue-262083016
* [x] Michael Winterberg (mwinterb): https://github.com/fmtlib/fmt/pull/1089#issue-263072033
* [x] Mario Werner (niosHD): https://github.com/fmtlib/fmt/issues/1073#issuecomment-475152902
* [x] Lars Gullik Bjønnes: https://github.com/fmtlib/fmt/issues/1073#issuecomment-476341407
* [x] Olaf Hering (olafhering): https://github.com/fmtlib/fmt/pull/1091#issue-264192287
* [x] Billy Donahue (BillyDonahue): https://github.com/fmtlib/fmt/pull/1099#issue-265774707
* [x] Mark Stapper (starkmapper): https://github.com/fmtlib/fmt/pull/1079#issuecomment-473344999
* [x] Lectem: https://github.com/fmtlib/fmt/pull/1103#issue-266422186
* [x] Alex Alabuzhev (alabuzhev): https://github.com/fmtlib/fmt/issues/1073#issuecomment-479429184
* [x] remyabel: https://github.com/fmtlib/fmt/pull/1102#issue-266027499
* [x] Bruce Mitchener (waywardmonkeys): https://github.com/fmtlib/fmt/pull/1107#issue-268302121
* [x] Dean Moldovan (dean0x7d): https://github.com/fmtlib/fmt/issues/1073#issuecomment-481126410
* [x] medithe: https://github.com/fmtlib/fmt/issues/1073#issuecomment-481581403
* [x] Alexander Bolz (abolz): https://github.com/fmtlib/fmt/issues/1073#issuecomment-481712790
* [x] Mathias Winterhalter (ToolsDevler): https://github.com/fmtlib/fmt/pull/1093#issue-264949681
* [x] Remotion: https://github.com/fmtlib/fmt/issues/1073#issuecomment-483701815
* [x] Tao He (sighingnow): https://github.com/fmtlib/fmt/pull/1121#issue-271560821
* [x] Nicolas (Rakete1111): https://github.com/fmtlib/fmt/issues/1073#issuecomment-484815510
* [x] Jamboree: https://github.com/fmtlib/fmt/pull/173#issuecomment-485062661
* [x] Sign Bit / Florin Iucha (0x8000-0000): https://github.com/fmtlib/fmt/issues/1073#issuecomment-485135792
* [x] morinmorin: https://github.com/fmtlib/fmt/issues/1073#issuecomment-485240216
* [x] Carter Li: https://github.com/fmtlib/fmt/issues/1073#issuecomment-485301296
* [x] Denis Blank (Naios): https://github.com/fmtlib/fmt/issues/1073#issuecomment-487219487
* [x] Paul Dreik (pauldreik): https://github.com/fmtlib/fmt/pull/1135#issue-274203396
* [x] denchat: https://github.com/fmtlib/fmt/pull/1134#issue-274199299
* [x] Greg Sjaardema (gsjaardema): https://github.com/fmtlib/fmt/pull/1139#issue-275724502
* [x] Gabi Melman (gabime): https://github.com/fmtlib/fmt/pull/780#issuecomment-491609594
* [x] Mateusz Janek (stryku): https://github.com/fmtlib/fmt/issues/1073#issuecomment-491615217
* [x] Michael Lui (mikelui): https://github.com/fmtlib/fmt/issues/1073#issuecomment-497356680
* [x] Candy Gumdrop: https://github.com/fmtlib/fmt/pull/875#issuecomment-520237265
* [x] Ingo van Lil (inguin): https://github.com/fmtlib/fmt/pull/218#issuecomment-520244182
* [x] jdale88: https://github.com/fmtlib/fmt/pull/28#issuecomment-520263615
* [x] Thomas Bernard (teajay-fr): https://github.com/fmtlib/fmt/issues/1073#issuecomment-520557908
* [x] hhggit: https://github.com/fmtlib/fmt/issues/1073#issuecomment-521695602
* [x] Andreas Schönle (AndreasSchoenle): https://github.com/fmtlib/fmt/issues/1073#issuecomment-522244480
* [x] Yassine (Ryuuke): https://github.com/fmtlib/fmt/pull/102#issuecomment-522571751
* [x] tnovotny: https://github.com/fmtlib/fmt/issues/1073#issuecomment-522749273

**Comment by mjcaisse** [comment]
Boost Software License (BSL) also has no binary requirement.

> Boost Software License - Version 1.0 - August 17th, 2003
>
> Permission is hereby granted, free of charge, to any person or organization
> obtaining a copy of the software and accompanying documentation covered by
> this license (the "Software") to use, reproduce, display, distribute,
> execute, and transmit the Software, and to prepare derivative works of the
> Software, and to permit third-parties to whom the Software is furnished to
> do so, all subject to the following:
>
> The copyright notices in the Software and this entire statement, including
> the above license grant, this restriction and the following disclaimer,
> must be included in all copies of the Software, in whole or in part, and
> all derivative works of the Software, unless such copies or derivative
> works are solely in the form of machine-executable object code generated by
> a source language processor.
>
> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
> IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
> FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
> SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
> FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
> ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
> DEALINGS IN THE SOFTWARE.

**Comment by vitaut** [comment]
List of current library contributors from blame: 

Alex Alabuzhev
Alexander Bolz
Andreas Schönle
Brian
Bruce Mitchener
Candy Gumdrop
Carter Li
Daniela Engert
Dean Moldovan
Denis Blank
Dhruv Paranjape
Dror Levin
Elias Kosunen
Glen Stark
Guillaume Fraux
Ingo van Lil
Johan J
Jonathan Müller
Lars Gullik Bjønnes
Magnus Bjerke Vik
Marek Kurdej
Mario Werner
Michael Lui
Michael Winterberg
MikePopoloski
Nicolas
Nils Moehrle
Remotion
Ryuuke
Sign Bit
Thomas Bernard
Tilman Keskinöz
Vasili Galka
Victor Zverovich
christinaa
codicodi
cstamford
gabime
gawain
hhggit
jdale88
morinmorin
stryku
tnovotny
vitaut

**Comment by DanielaE** [comment]
That's fine with me!

**Comment by eliaskosunen** [comment]
I agree to the changes

**Comment by ricco19** [comment]
By the way, I am the artist formerly known as just "Brian" on this list, so you can remove it.

**Comment by mwinterb** [comment]
As a note, mwinterb and Michael Winterberg are the same. Unless there's another Michael Winterberg out contributing :)

**Comment by niosHD** [comment]
Hi @vitaut, thank you for the ping in #513. I am fine with changing the license to drop all requirements on binary redistribution.

**Comment by LarsGullik** [comment]
I agree to the changes.

**Comment by alabuzhev** [comment]
No objections.

**Comment by dean0x7d** [comment]
I agree with changing the license!

**Comment by medithe** [comment]
I agree to the changes!

**Comment by abolz** [comment]
I agree to the changes.

**Comment by Remotion** [comment]
I agree to license changes as well.

**Comment by Rakete1111** [comment]
I agree as well :)

**Comment by 0x8000-0000** [comment]
I agree to the changes.

**Comment by morinmorin** [comment]
I agree to the changes.

**Comment by CarterLi** [comment]
That's ok with me.

**Comment by Naios** [comment]
I agree to the changes.

**Comment by stryku** [comment]
LGTM, I agree +1

**Comment by mikelui** [comment]
Late to the party. Agreed!

**Comment by nightlark** [comment]
Please stay far, far away from CLAs -- they are a huge pain that can add significant hurdles to contribution or even make it legally impossible to contribute.

My own experience with this has been with Microsoft/vcpkg; they require signing a CLA in order to open a PR to add a package. I sent the legal department at work an email asking for permission to sign the CLA at the beginning of the year -- it has not been approved because of some "indemnity clause", and they have offered no alternatives (nearly 6 months later). To be clear, the code for adding a package could legally be open sourced, but because of the CLA it would be impossible for me to contribute that change upstream. I've even asked if I could prepare the package and open the PR on my own time so that I could sign the individual CLA instead, and the answer was basically no (submitting the package would be too similar to the project I was getting paid to work on). This would basically apply no matter how trivial the change is.

Some of the writing on the subject (DCO would be much easier for contributors at companies than a CLA):
https://ben.balter.com/2018/01/02/why-you-probably-shouldnt-add-a-cla-to-your-open-source-project/
https://opensource.com/article/18/3/cla-vs-dco-whats-difference
https://about.gitlab.com/2017/11/01/gitlab-switches-to-dco-license/
https://software.llnl.gov/about/licenses/#developer-certificate-of-origin

Beyond that, an unmodified license that fulfills the requirements (Boost as suggested above?) might be easier to get past corporate legal departments than one with exceptions added (ZeroMQ LGPL with static linking exception raised some questions).

**Comment by vitaut** [comment]
BSD will continue to be an option so exception is not a problem.

**Comment by vitaut** [comment]
`fmt/core.h` contributors all accounted for except for authors of two small commits:

* @Zefz (JohanJansen): https://github.com/fmtlib/fmt/pull/959/commits/352ae74cf7209736b30087196490efc05c0cd45d
* @MikePopoloski: https://github.com/fmtlib/fmt/commit/b1d10a2884c6f18ea5694c315a554a3f87be8c2d

**Comment by teajay-fr** [comment]
I have no objections to changing the license terms.

**Comment by hhggit** [comment]
I agree to the changes.

**Comment by AndreasSchoenle** [comment]
I do of course agree to changing license terms in any way you see fit.

**Comment by tnovotny** [comment]
I am fine with the changes.

**Comment by vitaut** [comment]
The new license draft: https://github.com/fmtlib/fmt/blob/master/LICENSE.rst
